### ISSUE TITLE
Streamlining line number substitutions

### ISSUE THREAD

**Issue by TelosTelos** [Lonami/pyndustric#13]
Mlog uses line numbers to specify jump destinations, so it's important to get line numbers right, and it's difficult to alter compiled code (e.g., in an optimization pass) without taking great care to avoid messing up jump destinations.  Currently Pyndustric handles this by carefully building the program from beginning to end, with a sort of piecemeal substitution of line-numbers into forward-looking jump statements, once their destinations' line numbers become fixed.

It would be better to have a uniform mechanism for performing line-number substitutions, and probably also to delay making such substitutions until all line numbers have been finalized.  This will make handling of line-numbers much less piecemeal, aid in compiling `label()` and `jump_to()` function-calls, and make it much easier for us to implement things like optimization passes that end up changing line-numbers.

Here's the solution I'm currently leaning towards:

Create a new `Instruction` class, used to store a single mlog instruction.  These will be what are listed in the compiler's `._ins` attribute.  Such instructions are currently stored as strings, and some string methods are used on them, so `Instruction` could be made a subclass of `str` to preserve those uses.  The main new features that these would have is that they will eventually be assigned a `.linenumber` attribute indicating what line in the final code an instruction will have, and a `.no_op` attribute indicating whether this instruction should end up being included in the compiled code.  (This will allow us to put no-op placeholders like jump destination labels in the list of instructions, to mark a location in the code that should remain stable, even if the flanking instructions end up being re-written in an optimization pass. 

Create a new `Label` class, used to store information about a potential jump destination.  Some uses of Labels will be prettier if this is also made to be an `str` subclass with each label behaving like the string `"{labelname}"`.  The constructor for new Labels will ensure that each label has a unique `.name`, like `"endif_27"`.  Each label will have a `.destination`, indicating the destination instruction (usually a no-op placeholder) that that label will be used to jump to.  Instructions that should jump to that destination will initially contain `{labelname}` but this will eventually be replaced with the line number of that destination, once line numbers are finalized.

Once all optimization passes are through, assign each Instruction a `.linenumber` corresponding to its position in the finalized list of instructions (not counting no-op instructions).  Then create a `label_to_linenumber` dictionary mapping each Label's `.name` to the `.linenumber` of its `.destination`.  Once the near-final code is produced by concatenating the (op) instructions together into a single string, all the finalized line numbers can then be substituted into that string at once by using this dictionary as the mapping for Python's `str.format()`.

**Comment by Lonami** [comment]
> It would be better to have a uniform mechanism for performing line-number substitutions

Yes, I tried overengineering this solution by using some "instruction" class with jumps that could have "marks" (current's `'{}'` formatting) that would be filled up later or able to reference other "instructions". But I gave up because I wasn't much in the mood and wasn't necessary.

This approach seems similar to what you describe of instructions/labels.

This is how I see it:
* We have that `Instruction` (naming can change, whether it's a `str` or not doesn't matter).
* Jumps are a special subclass with a "jump location" which is another instruction.
* After compilation ends we construct a map `{instruction: lineno}` and fix-up all those jump locations.

Hmm… but this does break with optimization passes because the instruction reference is lost. So we introduce the label you suggest:


* We have that `Instruction`.
* Jumps have a "jump location" which is a label. Labels are special `Instruction` that *don't* increment the line number, and are not emitted into mlog.
* After compilation ends we construct a map `{label: lineno}` and fix-up all those jump locations.

Sounds good to me. This will require a few iterations over the entire program, but it's fine because they can be 1000 mlog instructions at most so at worst we'll need 1000 to create the lineno map and another 1000 to fix up the jump locations (map lookup is amortized O(1)).

**Comment by TelosTelos** [comment]
Yeah, I wouldn't worry about Big-O measures on data-sets this small, unless we end up doing some really weird combinatorics.

Anyway, I've already implemented this along the lines I suggested above, and it works great.  I also used this to rewrite and streamline all the code for conditional jumps in `if` and `while` statements.  Using labels for this makes our code for handling these shorter, more uniform, and more intuitive than your more ad hoc substitutions were.  Now `while` can use comparative tests just like `if` can, both of these will negate the test to reduce instruction-count, and logical `and`, logical `or`, and their negations can all be used, all evaluated greedily as Python coders would expect.

I haven't tried to mess around with _black_ yet, and doing so isn't a high priority for me (since the main impact on me will just be that it reformats my code in a way that is initially unfamiliar to me!) so it may be that you won't be interested in having me share these changes.  But if you are interested, I'd be happy to share them, as I think you'll probably find them to be a strict improvement over what you had, aside perhaps from quibbles with my formatting and/or profuse commentary.

**Comment by Lonami** [comment]
Yes, a pull request with the label changes to cleanup line number handling would be appreciated. Just run *Black* on your code and it'll be good, the CI should complain if you don't (or send the PR as is, I'll run *Black*, and then I can merge).

**Comment by TelosTelos** [comment]
Ok, I committed my current version to my fork, and passed that on in a pull-request to you, though I didn't blacken it, and it still contains profuse comments and TODO's that you may not like.  Feel free to take as much or as little as you like...

**Comment by Lonami** [comment]
Fixed by https://github.com/Lonami/pyndustric/commit/f8441abbc059241ca3d224d7c0619aaa824384b8.

When a reference to a line needs to be used in a `_Jump` `_Instruction`, a new `_Label` object instance is created. This instance is unique, and a reference to it is stored in the jump.

When generating code, a first pass assigns the correct line numbers to all labels. A second pass iterates over all instructions and represents them as strings, skipping labels. Jumps which reference labels have access to the label's line number at this point, so they can be correctly represented as strings.
