### ISSUE TITLE
Support compilation of defined functions and Path

### ISSUE THREAD

**Issue by Lonami** [Lonami/pyndustric#15]
Split off https://github.com/Lonami/pyndustric/pull/12/files#diff-852dce7acd90bf3bfbde1cec63522f7204b9c209cc52b3e40d23bb6f3202ef7fR39.

Currently `compile` only accepts a string with the Python code. It should also support `Path`, file-like objects, or functions.

**Comment by TelosTelos** [comment]
I just committed changes to [my fork](https://github.com/TelosTelos/pyndustric) that enable function arguments to compile().  This makes articulation of tests in test_all look a lot cleaner than dedented """-strings.  (I haven't bothered with file-Path arguments yet -- not a priority for me because I probably wouldn't use it.)  

This was a fairly self-contained change that you'd probably want, so I was thinking of giving you a new pull request for it, but Github apparently won't let me create a new pull request for my fork (or maybe I'm incompetent, or maybe both).  So, anyway, it's there if you want it (though of course you'll have to disentangle it from whatever parts of my fork you don't want, probably mostly just profuse comments and TODO's).

**Comment by Lonami** [comment]
> Github apparently won't let me create a new pull request for my fork

The way contributing to other repositories works generally is as follows:
* Fork the repository you want to send a patch to.
* Clone your fork.
* Create a new *branch* to work on a *specific* change (GitHub allows one active PR per branch).
* Work on your changes in *small*, self-contained commits.
* Push your changes to the same remote branch.
* From your fork's UI, send a pull request.

If you don't want to go through the process of making small commits, I guess I could cherry pick what I need myself, it's just unfortunate it'll be under my name I think.

**Comment by TelosTelos** [comment]
I doubt I'll do all that incremental stuff, e.g., because it'd need to be done in files without the comments and TODO's that I find useful, because a lot of the changes I'm planning are interdependent, because I'm not sure how many of them you'd want anyway, because it would consume time without producing appreciable benefits, etc...  

By the end of the process, I'll probably have significantly altered the majority of what you wrote, e.g. to streamline substitution of line numbers, to make conditional jumps more efficient with more functionality, to completely rework expression handling so it can handle arbitrary complexity and vectorized operations, to replace the stack with more efficient dummy variable usage, to add a new object-oriented interface for unit control, and to rework the interface for block control to match that.  By that point, many of the TODO's you didn't like will have evaporated, though it likely will be polluted with more/different comments than you'd like.  My guess is that both of our lives would be made easier if you just keep an eye on my progress, determine which of my versions is the last one you kind of liked and blacken it and prune out the comments you don't like, rather than trying to make each of my many incremental changes along the way conform to your format expectations.  But tis up to you -- I'm happy to keep making my current versions available to you and the world, so you're free to grab from it incrementally if you want, and I very much appreciate the ideas and suggestions you've offered.

**Comment by Lonami** [comment]
Functions were implemented earlier in https://github.com/Lonami/pyndustric/commit/18fac3d6b3db5b58402b20465999b0bcccdfb856.
