### ISSUE TITLE
While conditions could be more efficient

### ISSUE THREAD

**Issue by Lonami** [Lonami/pyndustric#18]
Split off https://github.com/Lonami/pyndustric/pull/12/files#diff-852dce7acd90bf3bfbde1cec63522f7204b9c209cc52b3e40d23bb6f3202ef7fR197-R206.

If the test is a comparision, the same optimization as it's done for `if` should be performed.

A cycle can be saved if trivial comparisions instructions are duplicated, so that rather than unconditionally jumping to the check, perform the check in both places. Note that this might be better suited for an optimization pass that detects inconditional jumps to conditional jumps, and replaces those. Note that this is not trivial if that second jump relies on other variables, which would need to be checked to make sure they exist.

**Comment by TelosTelos** [comment]
I think all this was fixed in my version when I reworked conditional jumps yesterday.

I'm not sure I understood the final concern you expressed?  Here's an example of a repeated-test while loop.
This source code:
```python
        x = 10
        while x>5:
            x -= 1
        z = 1
```
Compiles (in my version) to:
```
        set x 10
        jump 5 lessThanEq x 5
        op sub x x 1
        jump 3 greaterThan x 5
        set z 1
```
You'll note that the two tests (incorporated in the two jump commands) are negations of each other, because the upper jump _escapes_ the loop when the given test (x>5) is _false_, whereas the latter jump _repeats_ the loop when the given test is _true_.

As far as I can tell, this sort of setup will always have the upper and lower test depend on the same variables, so I don't see why why we'd need to check if they exist.  Also, technically I think mlog makes every first-referenced variable pop into existence with value 0, so it's pretty hard to test if a variable doesn't exist -- just mentioning it makes it pop into existence!  (This strangely parallels a crazy argument Bishop Berkeley made long ago that everything that exists is conceived by some mind.  Any alleged counterexample you might come up with will be one conceived in your mind, so won't be a counter-example after all!)

**Comment by Lonami** [comment]
You're right there's no need to check for existence, I was thinking that the loop condition would use a variable created in the body of the `while`. But the transformation (uncoditional jump, conditional) is equivalent to just doing the conditional in the first place.

**Comment by Lonami** [comment]
Fixed with `conditional_jump` introduced by https://github.com/Lonami/pyndustric/commit/f8441abbc059241ca3d224d7c0619aaa824384b8.
