### ISSUE TITLE
What does complex assigment mean?

### ISSUE THREAD

**Issue by Leo-MathGuy** [Lonami/pyndustric#53]

**Comment by Lonami** [comment]
It depends on your code, but it's essentially a compiler limitation (the compiler doesn't know to compile certain assignments yet, because the code to do that has not been implemented).

I'm going to close this as it's just a question but if you would like the compiler to support a certain (particular, concrete) assignment, don't hesitate to open another issue.

**Comment by Leo-MathGuy** [comment]
It was just that i did link.enabled = true instead of link.enabled(true)
